companieshouse/chips-terraform

- groups/chips-ef-batch/main.tf
- groups/chips-tux-proxy/main.tf
- groups/chips-users-rest/main.tf
Specify additional ingress rules to allow access to tuxedo ports from the application subnet - this allows the chips-tux-proxy to talk to the chips-ef-batch & chips-rest-users clusters and also the NLB to talk to the chips-tux-proxy.
Resolves https://companieshouse.atlassian.net/browse/CM-895
> Add additional ingress rules for tuxedo

- groups/chips-ef-batch/main.tf
- groups/chips-tux-proxy/main.tf
- groups/chips-users-rest/main.tf
This pulls in the change to allow ingress from CHS cidrs for http/https REST calls
Resolves: https://companieshouse.atlassian.net/browse/CM-943
> Advance version of chips-app terraform module to 1.0.94

- groups/chips-ef-batch/profiles/heritage-development-eu-west-2/vars
- groups/chips-ef-batch/profiles/heritage-live-eu-west-2/vars
- groups/chips-ef-batch/profiles/heritage-staging-eu-west-2/vars
- groups/chips-tux-proxy/profiles/heritage-development-eu-west-2/vars
- groups/chips-tux-proxy/profiles/heritage-live-eu-west-2/vars
- groups/chips-tux-proxy/profiles/heritage-staging-eu-west-2/vars
- groups/chips-users-rest/profiles/heritage-development-eu-west-2/vars
- groups/chips-users-rest/profiles/heritage-live-eu-west-2/vars
- groups/chips-users-rest/profiles/heritage-staging-eu-west-2/vars
Adds the log group/file definitions for the application logs (WebLogic/Apache/EAI/SSO), and also adds the live vars needed for the infrastructure deployment to heritage-live.
Resolves: https://companieshouse.atlassian.net/browse/CM-992
> Add application log groups and live config

- groups/chips-ef-batch/main.tf
- groups/chips-tux-proxy/main.tf
- groups/chips-users-rest/main.tf
This pulls in the change done to reduce the size of the IAM policy by only writing one resource entry for each log group.
Resolves: https://companieshouse.atlassian.net/browse/CM-992
> Reference version 1.0.96 of chips-app module

- groups/staffware-db/profiles/heritage-staging-eu-west-2/vars
Changing instance type for staffware due to limitation on r5n options in AWS Zones
> Changing instance type for staffware due to limitation on r5n options in AWS Zones

- groups/chips-rds/profiles/heritage-development-eu-west-2/vars
Removed sec_case_sensitive_logon from parameter group params as it's no longer configurable in Oracle 19
Corrected `engine_version` value
> Update development vars for deployment

- groups/chips-rds/profiles/heritage-development-eu-west-2/vars
Updated parameter_group parameters to allow Toad access on Oracle 19 RDS
* sqlnetora.sqlnet.allowed_logon_version_client -> "10"
* sqlnetora.sqlnet.allowed_logon_version_server -> "10"
Resolves: CM-1092
> Update RDS Parameters for Toad Access on Oracle 19

- groups/chips-tux-proxy/main.tf
Stop creating an NLB for the chips-tux-proxy group.  I've left the capability/functionality in the chips-app module, in case it is needed in future, and just removed the setting of the `create_tuxedo_nlb` var, so it uses its default value of false.
Resolves: https://companieshouse.atlassian.net/browse/CM-1119
> Disable the creation of the tuxedo NLB

- groups/chips-ef-batch/main.tf
- groups/chips-ef-batch/profiles/heritage-development-eu-west-2/vars
- groups/chips-ef-batch/variables.tf
- groups/chips-tux-proxy/main.tf
- groups/chips-tux-proxy/profiles/heritage-development-eu-west-2/vars
- groups/chips-tux-proxy/variables.tf
- groups/chips-users-rest/main.tf
- groups/chips-users-rest/profiles/heritage-development-eu-west-2/vars
- groups/chips-users-rest/variables.tf
Adds a var `enable_instance_refresh` that has a default of false.  This is overridden by setting to true in the heritage-development environment.
This var value is then passed into the chips-app ASG module, so we can stop instances being refreshed automatically. We need to disable instance refresh in live to avoid impacting users/traffic with a rolling refresh.
Resolves: https://companieshouse.atlassian.net/browse/CM-1127
> Disable instance refresh in staging and live environments

- groups/chips-ef-batch/data.tf
- groups/chips-ef-batch/main.tf
- groups/chips-ef-batch/profiles/heritage-development-eu-west-2/vars
- groups/chips-ef-batch/profiles/heritage-live-eu-west-2/vars
- groups/chips-ef-batch/profiles/heritage-staging-eu-west-2/vars
- groups/chips-ef-batch/variables.tf
- groups/chips-tux-proxy/data.tf
- groups/chips-tux-proxy/main.tf
- groups/chips-tux-proxy/profiles/heritage-development-eu-west-2/vars
- groups/chips-tux-proxy/profiles/heritage-live-eu-west-2/vars
- groups/chips-tux-proxy/profiles/heritage-staging-eu-west-2/vars
- groups/chips-tux-proxy/variables.tf
- groups/chips-users-rest/data.tf
- groups/chips-users-rest/main.tf
- groups/chips-users-rest/profiles/heritage-development-eu-west-2/vars
- groups/chips-users-rest/profiles/heritage-live-eu-west-2/vars
- groups/chips-users-rest/profiles/heritage-staging-eu-west-2/vars
- groups/chips-users-rest/variables.tf
Add CHIPS mounts for staging to support writing to dbclobs, fes_dbclobs and reading from the test_image share.
The NFS config was previously hardcoded and this has now been moved into vault under the path
`/applications/<account>-eu-west-2/chips/app/nfs_mounts`
(where <account> is heritage-development, heritage-staging or heritage-live
There is a key present under that path for each of the current application types, chips-user-rest-mounts, chips-ef-batch-mounts & chips-tux-proxy-mounts and the value of that key is a map of NFS mounts as expected by the ansible code here: https://github.com/companieshouse/ansible-collections/blob/main/ch_collections/heritage_services/roles/nfs/files/nfs_mounts/templates/mounts.j2
The map is of the form:
```
{
"application_root": {
"local_mount_point": …
```
> Add batt14 and image mounts for staging

- groups/staffware-db/data.tf
- groups/staffware-db/ec2.tf
- groups/staffware-db/profiles/heritage-staging-eu-west-2/vars
- groups/staffware-db/variables.tf
Adding new rule for iprocess app access to DB instance, adding option to hardcode AMI Id to stop instance rebuilds when new AMIs are avaiable
> Adding new rule for iprocess app access to DB instance

- groups/staffware-app/asg_frontend.tf
Updated ASG security group to permit WebLogic app connectivity from on-premise
> Permit application connectivity from on-premise

- groups/chips-ef-batch/main.tf
- groups/chips-tux-proxy/main.tf
- groups/chips-users-rest/main.tf
This adds a call to the WebLogic Pre Bootstrap script which "unlocks" any locked files on the NFS that can sometimes be encountered after a hard restart.
Resolves: https://companieshouse.atlassian.net/browse/CM-1190
> Call weblogic-pre-bootstrap.sh on startup prior to bootstrap

- groups/staffware-app/asg_frontend.tf
- groups/staffware-app/data.tf
- groups/staffware-db/data.tf
- groups/staffware-db/ec2.tf
Adds ingress rules to allow access fro CHIPS WebLogic app to the iProcess DB and application.
Resolves: https://companieshouse.atlassian.net/browse/CM-1169
> Allow access from CHIPS app to iProcess application and database

- groups/staffware-app/asg_frontend.tf
The last update to add the CHIPS app didn't work as I missed updating the `number_of_computed_ingress_with_source_security_group_id` entry.  This updates the terraform to change `computed_ingress_with_source_security_group_id` to `ingress_with_source_security_group_id` so that line is no longer needed and to bring the config in line with the DB security groups.
Resolves: https://companieshouse.atlassian.net/browse/CM-1169
> Update ingress rule to remove computed

- groups/chips-ef-batch/main.tf
- groups/chips-tux-proxy/main.tf
- groups/chips-users-rest/main.tf
Reference 1.0.111 of terraform-modules to bring in security group changes to allow http/s access to CHIPS ALBs from application subnets.
Resolves: https://companieshouse.atlassian.net/browse/CM-1177
> Allow FES access to CHIPS ALB

- groups/chips-db/ec2.tf
- groups/chips-db/sns.tf
- groups/chips-rep-db/ec2.tf
- groups/staffware-db/ec2.tf
Adding EC2 cloudwatch alarms to each Oracle DB EC2 group, SNS only deployed to CHIPS and will be reused
> Adding EC2 cloudwatch alarms to each Oracle DB EC2 group, SNS only deployed to CHIPS and will be reused

- groups/chips-db/iam.tf
- groups/chips-db/ssm.tf
- groups/chips-db/templates/chips-db-failover-ssm-document.yaml
templated ssm document added to produce SSM Automation RunBook to power on the failover chips DB instance, wait for availability and then trigger a configuration command document.
execution role provided with minimal permissions
> chips db failover run book

- groups/chips-tux-proxy/profiles/heritage-live-eu-west-2/vars
- groups/chips-tux-proxy/profiles/heritage-staging-eu-west-2/vars
We have noticed that the proxies are getting restarted and that the EC2 instance is low on memory.  This changes the instance from a t3.medium to a t3.large.
t3.large has the same vCPUs but double the memory, so there is no additional WL licensing cost.
> Increase tux-proxy instances size

- groups/chips-ef-batch/main.tf
- groups/chips-tux-proxy/main.tf
- groups/chips-users-rest/main.tf
Reference 1.0.126 of chips-app terraform module to bring in ability to disable the app target group.
Resolves: https://companieshouse.atlassian.net/browse/CM-1195
> Disable app target group for chips-tux-proxy cluster

- groups/chips-ef-batch/main.tf
- groups/chips-tux-proxy/main.tf
- groups/chips-users-rest/main.tf
Allow ingress to http and t3s ports on WebLogic from within the application subnets, to allow for monitoring, analytics and comms between clusters.
Resolves: https://companieshouse.atlassian.net/browse/CM-1123
> Add ingress rules for direct http & t3s traffic to WebLogic nodes

- groups/chips-read-only/profiles/heritage-live-eu-west-2/vars
- groups/chips-read-only/profiles/heritage-staging-eu-west-2/vars
There should only be one instance in this cluster, as it will only be used occasionally for short periods, so having 2 instances would be wasteful.
Resolves: https://companieshouse.atlassian.net/browse/CM-1335
> Correct the ASG count to 1 for staging and live

- groups/chips-ef-batch/main.tf
- groups/chips-read-only/main.tf
- groups/chips-tux-proxy/main.tf
- groups/chips-users-rest/main.tf
This pulls in the change to add an NLB in front the ALB in order to provide static IPs to allow NAT access from call centre network.
The NLB is only created if the module var create_nlb = true, and it is not created by default. The intention is to just create this for the chips-users-rest cluster.
Resolves: https://companieshouse.atlassian.net/browse/CM-1374
> Update referenced version of terraform-modules to 1.0.163

- groups/chips-db/ec2.tf
- groups/chips-db/iam.tf
- groups/chips-db/profiles/heritage-live-eu-west-2/vars
- groups/chips-db/profiles/heritage-staging-eu-west-2/vars
- groups/chips-db/variables.tf
- groups/chips-rep-db/ec2.tf
- groups/chips-rep-db/iam.tf
- groups/chips-rep-db/profiles/heritage-live-eu-west-2/vars
- groups/chips-rep-db/profiles/heritage-staging-eu-west-2/vars
- groups/chips-rep-db/variables.tf
- groups/staffware-db/ec2.tf
- groups/staffware-db/iam.tf
- groups/staffware-db/profiles/heritage-live-eu-west-2/vars
- groups/staffware-db/profiles/heritage-staging-eu-west-2/vars
- groups/staffware-db/variables.tf
Added config to define and create CloudWatch log groups in readiness to receive Oracle DB logs
Added list variable to define the log groups by name
Added new `aws_cloudwatch_log_group` resource to create the log groups defined in the list
Updated the `db_instance_profile` module to include the Oracle log group names in the instance IAM policy
> Create CloudWatch Log Groups for Oracle Logs

- groups/chips-db/data.tf
- groups/chips-db/locals.tf
- groups/chips-rep-db/data.tf
- groups/chips-rep-db/locals.tf
- groups/staffware-db/data.tf
- groups/staffware-db/locals.tf
Added data sources to obtain deployment CIDR ranges from Vault
Added local to extract CIDR list
Updated `ssh_allowed_ranges` to include the `deployment_cidrs`
Changes made for:
* chips-db
* chips-rep-db
* staffware-db
> Allow Concourse Deployment Connectivity

- groups/chips-db-batch/asg.tf
- groups/chips-db-batch/data.tf
- groups/chips-db-batch/iam.tf
- groups/chips-db-batch/keys.tf
- groups/chips-db-batch/locals.tf
- groups/chips-db-batch/main.tf
- groups/chips-db-batch/profiles/heritage-development-eu-west-2/vars
- groups/chips-db-batch/profiles/heritage-live-eu-west-2/vars
- groups/chips-db-batch/profiles/heritage-staging-eu-west-2/vars
- groups/chips-db-batch/sns.tf
- groups/chips-db-batch/templates/user_data.tpl
- groups/chips-db-batch/variables.tf
- groups/chips-db-batch/version
Adds a new group to create a chips-db-batch instance (using an ASG for resilience).  This is to be used to run oltp, rep & fes batch docker containers.
Resolves: https://companieshouse.atlassian.net/browse/CM-1435
> Add chips-db-batch group

- groups/staffware-app/iam.tf
Adding permission to allow use of ASG name tag in CM-1414 cloudwatch
config
> Add autoscaling describe permission

- groups/chips-db/ec2.tf
- groups/chips-db/profiles/heritage-live-eu-west-2/vars
- groups/chips-db/profiles/heritage-staging-eu-west-2/vars
- groups/chips-db/variables.tf
- groups/chips-rep-db/ec2.tf
- groups/chips-rep-db/profiles/heritage-live-eu-west-2/vars
- groups/chips-rep-db/profiles/heritage-staging-eu-west-2/vars
- groups/chips-rep-db/variables.tf
- groups/staffware-db/ec2.tf
- groups/staffware-db/profiles/heritage-live-eu-west-2/vars
- groups/staffware-db/profiles/heritage-staging-eu-west-2/vars
- groups/staffware-db/variables.tf
Added module config to deploy CloudWatch log filters and alarms for `chips-db`, `chips-rep-db` and `staffware-db`
Added supporting variables
Populated profile vars to match deployments
Alarm actions are currently disabled to prevent notification spam while they settle
Partially Resolves: CM-1427
> Add Standardised Oracle DB CloudWatch Alarms

- groups/staffware-app/asg_frontend.tf
Adding the following alarms to monitor EC2 instances within the ASG:
- CPUUtilization > 90%
- mem_used_percent > 90%
- disk_used_percent > 90%
> CM-1414 Add ASG-level EC2 alarms for staffware app

- groups/staffware-app/asg_frontend.tf
Editing alarm names and descriptions to add AWS account name (as in
existing ALB alarms) so that origin of alarm is clear for CSI emails.
(Also added AWS account name to name of pre-existing staffware app ASG alarms.)
> CM-1414 editing alarms to add AWS account name

- groups/chips-db/profiles/heritage-staging-eu-west-2/vars
Updated vars to add BCD RDS security group pattern to permit acecss to CHIPS OLTP
Resolves: INC0356915
> Allow BCD RDS to access CHIPS OLTP

- groups/chips-ef-batch/main.tf
- groups/chips-read-only/main.tf
- groups/chips-tux-proxy/main.tf
- groups/chips-users-rest/main.tf
This brings in a change to allow access for http/https to the CHIPS ALBs from the CIDRs defined in vault at /applications/<account>-<region>/chips/client_cidrs
Resolves:
https://companieshouse.atlassian.net/browse/CM-1374
> Reference 1.0.175 of chips-app terraform module

- groups/chips-db/ec2.tf
- groups/chips-rds/rds.tf
- groups/chips-rep-db/ec2.tf
- groups/staffware-db/ec2.tf
Updated existing RDS alarms module to use updated terraform module path and version
Updated variable names to match updated module requirements
Set `alarm_name_prefix` appropriately
> Update Oracle Alarms

- groups/chips-db/ec2.tf
- groups/chips-rep-db/ec2.tf
Bumped `oracledb_cloudwatch_alarms` module version
Enabled Oracle Streams alarm
Resolves: CM-1460
> Add Oracle Streams Alerting

- groups/chips-db/profiles/heritage-live-eu-west-2/vars
- groups/chips-db/profiles/heritage-staging-eu-west-2/vars
- groups/chips-rep-db/profiles/heritage-live-eu-west-2/vars
- groups/chips-rep-db/profiles/heritage-staging-eu-west-2/vars
- groups/staffware-db/profiles/heritage-live-eu-west-2/vars
- groups/staffware-db/profiles/heritage-staging-eu-west-2/vars
Allow connections to the CHIPS OLTP, REP & Staffware Oracle databases from the chips-db-batch EC2 instance.
https://companieshouse.atlassian.net/browse/CM-1436
https://companieshouse.atlassian.net/browse/CM-1437
> Allow access to oltp, rep & staffware DBs from chips-db-batch

- groups/chips-db/ec2.tf
- groups/chips-db/locals.tf
- groups/chips-db/profiles/heritage-staging-eu-west-2/vars
- groups/chips-db/variables.tf
- groups/chips-rep-db/ec2.tf
- groups/chips-rep-db/locals.tf
- groups/chips-rep-db/profiles/heritage-staging-eu-west-2/vars
- groups/chips-rep-db/variables.tf
- groups/staffware-db/ec2.tf
- groups/staffware-db/locals.tf
- groups/staffware-db/profiles/heritage-staging-eu-west-2/vars
- groups/staffware-db/variables.tf
Added vars to control whether EC2 instances are included in an AWS Backup plan
Added local to define the required instance tag and value
Updated EC2 instance resource to include the local in the tag map
Added Staging vars to enable the plan tag
Resolves: CM-1479
> Add AWS Backup tags to Staging DB Instances

- groups/chips-rep-db/data.tf
- groups/chips-rep-db/locals.tf
Added vault data lookup and local var for non-VPC CIDRs requiring Oracle access for DBLink
Updated `oracle_allowed_ranges` local to include the DBLink CIDRs
Resolves: INC0358786
> Allow DBLink to Chips REP

- groups/chips-ef-batch/profiles/heritage-development-eu-west-2/vars
- groups/chips-ef-batch/profiles/heritage-staging-eu-west-2/vars
- groups/chips-read-only/profiles/heritage-development-eu-west-2/vars
- groups/chips-read-only/profiles/heritage-live-eu-west-2/vars
- groups/chips-read-only/profiles/heritage-staging-eu-west-2/vars
- groups/chips-tux-proxy/profiles/heritage-development-eu-west-2/vars
- groups/chips-tux-proxy/profiles/heritage-staging-eu-west-2/vars
- groups/chips-users-rest/profiles/heritage-development-eu-west-2/vars
- groups/chips-users-rest/profiles/heritage-live-eu-west-2/vars
- groups/chips-users-rest/profiles/heritage-staging-eu-west-2/vars
Part of tidy-up work for CM-1467 - ensuring logs are ingested by Cloudwatch as reducing retention time on server.
> Correct chipsdomain.log filename in all profiles

- groups/chips-db-batch/asg.tf
- groups/chips-db-batch/data.tf
- groups/chips-ef-batch/main.tf
- groups/chips-read-only/main.tf
- groups/chips-tux-proxy/main.tf
- groups/chips-users-rest/main.tf
Reference 1.0.182 of chips-app module to allow SSH access from chips-control to chips-users-rest, chips-ef-batch,
chips-read-only and chips-tux-proxy EC2 instances.
Also allow SSH access from chips-control to chips-db-batch instance by adding security group ingress rule.
Resolves:
https://companieshouse.atlassian.net/browse/CM-1493
> Allow ingress from chips-control to chips instances

- groups/chips-db-batch/profiles/heritage-live-eu-west-2/vars
- groups/chips-db-batch/profiles/heritage-staging-eu-west-2/vars
Adding log groups for move-scan-files and fes-file-loader scripts. Only ingesting system script logs, not housekeeping/monitoring/reporting.
Also adjusting retention of existing staging logs to be consistently 7d, and adding fes-out & dps-out definitions to live.
> Ingest fes batch logs [CM-1438]

- groups/chips-ef-batch/main.tf
- groups/chips-ef-batch/profiles/heritage-live-eu-west-2/vars
- groups/chips-ef-batch/variables.tf
- groups/chips-read-only/main.tf
- groups/chips-read-only/profiles/heritage-live-eu-west-2/vars
- groups/chips-read-only/variables.tf
- groups/chips-tux-proxy/main.tf
- groups/chips-tux-proxy/profiles/heritage-live-eu-west-2/vars
- groups/chips-tux-proxy/variables.tf
- groups/chips-users-rest/main.tf
- groups/chips-users-rest/profiles/heritage-live-eu-west-2/vars
- groups/chips-users-rest/variables.tf
Override the default list of source security groups for SSH access to allow ingress from the analytics/grafana server.
This is only required in Live.
Resolves:
https://companieshouse.atlassian.net/browse/CM-1509
> Allow SSH access from sgr-gfn-app-001-* in Live

- groups/chips-reginit/locals.tf
This is so we can restore the db from rep to reginit. reginit does not need backing up
> updating backup bucket to point to rep

- groups/chips-reginit/ec2.tf
Adding the backup21 tag for the root and us01 disk, backup not required for 7tb disk
> adding backup tag

- groups/staffware-rds/data.tf
- groups/staffware-rds/rds.tf
Allow the chips-devtest and iProcess app instances access to the staffware/iProcess RDS DBs
> Allow ingress to 1521 from Weblogic and iProcess apps

- groups/chips-ef-batch/main.tf
- groups/chips-ef-batch/profiles/heritage-staging-eu-west-2/vars
- groups/chips-ef-batch/variables.tf
- groups/chips-tux-proxy/main.tf
- groups/chips-tux-proxy/profiles/heritage-staging-eu-west-2/vars
- groups/chips-tux-proxy/variables.tf
- groups/chips-users-rest/main.tf
- groups/chips-users-rest/profiles/heritage-development-eu-west-2/vars
- groups/chips-users-rest/profiles/heritage-staging-eu-west-2/vars
- groups/chips-users-rest/variables.tf
Adds a command to the user data script, to call the AppDynamics machine agent start script on chips-users-rest0 on development, and chips-users-rest0/1, chips-ef-batch0/1 and chips-tux-proxy0/1 on staging.
Resolves:
https://companieshouse.atlassian.net/browse/CM-1542
> Add post bootstrap command to allow start of AppDynamics machine agent

- groups/staffware-db/data.tf
- groups/staffware-db/ec2.tf
- groups/staffware-db/locals.tf
Allow access form CHS application subnets to the Staffware Oracle DB server on port 1521.  This is to allow the CHS Transaction Search Tool to connect to the Staffware DB.
Resolves:
https://companieshouse.atlassian.net/browse/CM-1545
> Add ingress from CHS app subnets to port 1521 on Staffware DB

- groups/chips-ef-batch/main.tf
- groups/chips-read-only/main.tf
- groups/chips-tux-proxy/main.tf
- groups/chips-users-rest/main.tf
Update the version of chips-app module used, to bring in an override to the client TLS error alarm threshold.
> Reference 1.0.187 of chips-app module

- groups/chips-ef-batch/main.tf
- groups/chips-read-only/main.tf
- groups/chips-tux-proxy/main.tf
- groups/chips-users-rest/main.tf
Passes the existing ami_name var through to the underlying chips-app module so that the pipeline can set the version of the docker-ami image.
https://companieshouse.atlassian.net/browse/CM-1550
> Pass ami_name var through to chips-app module

- groups/chips-reginit/ec2.tf
- groups/chips-reginit/locals.tf
- groups/chips-reginit/sns.tf
- groups/chips-reginit/variables.tf
These changes replace the current set of security group rules with prefix list associations which will include the iboss range as well as VPN and internal CIDR ranges.
> Rework reginit security group rules

- groups/staffware-app/data.tf
- groups/staffware-app/iam.tf
- groups/staffware-app/locals.tf
- groups/staffware-app/parameter-store.tf
- groups/staffware-app/templates/user_data.tpl
The iprocess-app-001 (Tibco iProcess/Staffware) EC2 instances contain sensitive data within the user data on the ch-heritage-dev, heritage-staging and heritage-live accounts. 
This change is to avoid embedding the sensitive data in the user data script and instead use parameter store, and access the data from there when the script runs.
Resolves:
https://companieshouse.atlassian.net/browse/DVOP-2675
> Avoid embedding sensitive data in the user data script

- groups/chips-db/data.tf
- groups/chips-db/ec2.tf
- groups/chips-db/locals.tf
- groups/chips-db/profiles/heritage-staging-eu-west-2/vars
- groups/chips-db/variables.tf
Enabling Test & migration Access via new SG's
One SG for [Staging](https://companieshouse.service-now.com/now/nav/ui/classic/params/target/incident.do%3Fsys_id%3D852a4f3c979e5190fb3a3a1f2153afa3%26sysparm_view%3D%26sysparm_domain%3Dnull%26sysparm_domain_scope%3Dnull%26sysparm_record_row%3D28%26sysparm_record_rows%3D81%26sysparm_record_list%3Dactive%253dtrue%255eassignment_group%253djavascript%253agetMyGroups()%255estate!%253d6%255eORDERBYsys_created_on) & one SG for [Live](https://companieshouse.service-now.com/now/nav/ui/classic/params/target/incident.do%3Fsys_id%3Dbf20507a97ce115006b37e371153af01%26sysparm_view%3D%26sysparm_domain%3Dnull%26sysparm_domain_scope%3Dnull%26sysparm_record_row%3D27%26sysparm_record_rows%3D81%26sysparm_record_list%3Dactive%253dtrue%255eassignment_group%253djava …
> Allow test migration access

- groups/chips-db-batch/iam.tf
- groups/chips-ef-batch/main.tf
- groups/chips-read-only/main.tf
- groups/chips-tux-proxy/main.tf
- groups/chips-users-rest/main.tf
- groups/staffware-app/iam.tf
Attach the managed policy that allows Inspector CIS scanning to the chips-db-batch and staffware-app groups and reference 0.1.251 of the chips-app module to bring the same change in for chips-users-rest, chips-ef-batch, chips-read-only & chips-tux-proxy groups.
https://companieshouse.atlassian.net/browse/DVOP-2793
> Add policy to allow AWS Inspector CIS scanning to CHIPS application tier instances

- groups/chips-db/iam.tf
- groups/chips-db/variables.tf
- groups/chips-oem/iam.tf
- groups/chips-oem/variables.tf
- groups/chips-reginit/iam.tf
- groups/chips-reginit/variables.tf
- groups/chips-rep-db/iam.tf
- groups/chips-rep-db/variables.tf
- groups/staffware-db/iam.tf
- groups/staffware-db/variables.tf
Add managed policy to allow CIS scanning by Inspector.
Note that just because this policy is present, it doesn't mean that we can actually run CIS scans without assessing the impact (to performance etc), so it is likely this will just be used on staging and not live for the main chips dbs.
https://companieshouse.atlassian.net/browse/DVOP-2793
> Add managed CIS scanning policy to db instance roles

- groups/staffware-rds/data.tf
- groups/staffware-rds/locals.tf
- groups/staffware-rds/profiles/heritage-development-eu-west-2/development/vars
- groups/staffware-rds/profiles/heritage-development-eu-west-2/training1/vars
- groups/staffware-rds/profiles/heritage-development-eu-west-2/training2/vars
- groups/staffware-rds/rds.tf
- groups/staffware-rds/variables.tf
Allows access based on source security group name patterns to staffware/iprocess RDS instances (development/training1/training2) for E2E/training weblogic and iprocess apps.
Also adds ca_cert_identifier var, with default of "rds-ca-rsa2048-g1" to match current infrastructure.
https://companieshouse.atlassian.net/browse/CHP-53
> Allow access to staffware/iprocess rds dev/training DBs by new E2E app envs

- groups/staffware-rds/profiles/heritage-development-eu-west-2/development/vars
- groups/staffware-rds/profiles/heritage-development-eu-west-2/training1/vars
- groups/staffware-rds/profiles/heritage-development-eu-west-2/training2/vars
Set `sqlnetora.sqlnet.expire_time=10` on the development, training1 & training2 Staffware RDS DB environments.  This matches a manual change previously applied to the development db, and also applies it to the training1 & 2 DBs for consistency.
Resolves:
https://companieshouse.atlassian.net/browse/CHP-233
> Set sqlnetora.sqlnet.expire_time=10

- groups/chips-ef-batch/main.tf
- groups/chips-read-only/main.tf
- groups/chips-tux-proxy/main.tf
- groups/chips-users-rest/main.tf
In support of recent ITHC security audit, enabling ELB deletion protection in:
* chips-ef-batch
* chips-read-only
* chips-tux-proxy
* chips-users-rest
> Enable ELB deletion protection

- groups/staffware-rds/profiles/heritage-development-eu-west-2/development/vars
Updates the SG patterns to allow access to dev Staffware RDS from the CHIPS E2E clone instances.
> Allow Staffware dev DB ingress from CHIPS E2E clone instances

- groups/chips-rep-db/profiles/heritage-live-eu-west-2/vars
This change ensures that the EC2 instance type for `chips-rep-db` instances matches our current AWS infrastructure.
> Update chips-rep-db EC2 instance type
