companieshouse/chips-terraform

- groups/chips-ef-batch/main.tf
- groups/chips-tux-proxy/main.tf
- groups/chips-users-rest/main.tf
Resolves https://companieshouse.atlassian.net/browse/CM-896
> Enable use of tuxedo NLB for chips-tux-proxy group

- groups/chips-ef-batch/main.tf
- groups/chips-tux-proxy/main.tf
- groups/chips-users-rest/main.tf
Update version of chips-app module to 1.0.93 to pull in changes to the ALB config.
Resolves: https://companieshouse.atlassian.net/browse/CM-930
> Update version of chips-app module to pull in alb changes

- groups/chips-db/templates/user_data.tpl
- groups/chips-rep-db/templates/user_data.tpl
- groups/staffware-db/profiles/heritage-staging-eu-west-2/vars
- groups/staffware-db/templates/user_data.tpl
Adding restart command to DB userdata and restoring count = 2 for staffware db
> Adding restart command to DB userdata and restoring count = 2 for staffware db

- groups/chips-ef-batch/main.tf
- groups/chips-tux-proxy/main.tf
- groups/chips-users-rest/main.tf
This brings in an IAM profile policy change to allow access to AWS Parameter Store.
Resolves: https://companieshouse.atlassian.net/browse/CM-1118
> Reference 1.0.101 of chips-app terraform module

- groups/chips-db/ssm.tf
- groups/chips-rep-db/ssm.tf
- groups/staffware-db/ssm.tf
Fixfor error "InvalidSchedule: ApplyOnlyAtCronInterval is not supported for No Schedule associations."
> fix for apply time error with schedules

- groups/chips-ef-batch/profiles/heritage-live-eu-west-2/vars
- groups/chips-ef-batch/profiles/heritage-staging-eu-west-2/vars
Add log groups for latest weblogic batch jobs
Resolves: https://companieshouse.atlassian.net/browse/CM-1102
> Add log groups for bulk-image-load and psc-pursuit-trigger jobs

- groups/chips-ef-batch/profiles/heritage-live-eu-west-2/vars
- groups/chips-ef-batch/profiles/heritage-staging-eu-west-2/vars
Added for staging/live.
CM-1100
> CM-1100: Added terraform logging group for batch image regeneration

- groups/chips-ef-batch/profiles/heritage-live-eu-west-2/vars
- groups/chips-ef-batch/profiles/heritage-staging-eu-west-2/vars
Cloudwatch log group added for officer-bulk-process in staging and live.
> CM-1101 - add officer-bulk-process log config

- groups/chips-ef-batch/main.tf
- groups/chips-tux-proxy/main.tf
- groups/chips-users-rest/main.tf
Resolves: https://companieshouse.atlassian.net/browse/CM-1300
> Reference 1.0.124 of chips-app module and set alb_idle_timeout=180

- groups/chips-ef-batch/main.tf
- groups/chips-ef-batch/profiles/heritage-live-eu-west-2/vars
- groups/chips-ef-batch/profiles/heritage-staging-eu-west-2/vars
- groups/chips-ef-batch/variables.tf
- groups/chips-tux-proxy/main.tf
- groups/chips-tux-proxy/profiles/heritage-live-eu-west-2/vars
- groups/chips-tux-proxy/profiles/heritage-staging-eu-west-2/vars
- groups/chips-tux-proxy/variables.tf
- groups/chips-users-rest/main.tf
- groups/chips-users-rest/profiles/heritage-live-eu-west-2/vars
- groups/chips-users-rest/profiles/heritage-staging-eu-west-2/vars
- groups/chips-users-rest/variables.tf
Resolves: https://companieshouse.atlassian.net/browse/CM-1195
> Reference 1.0.125 of chips-app module and enable alarms for ASG & ALB

- groups/chips-ef-batch/main.tf
- groups/chips-read-only/main.tf
- groups/chips-tux-proxy/main.tf
- groups/chips-users-rest/main.tf
This pulls in a fix for the call centre NLB, for cases where it is not being created.
Resolves: https://companieshouse.atlassian.net/browse/CM-1374
> Reference version 1.0.164 of chips-app module

- groups/chips-db/data.tf
- groups/chips-db/ec2.tf
- groups/chips-db/locals.tf
Added data-source to retrieve onprem CIDRs from Vault
Added local to decode secrets
Updated security group config to include onprem CIDRs
> Allow OLTP Access from OnPrem Apps

- groups/chips-rds/iam.tf
- groups/chips-rds/rds.tf
Added IAM resources to allow connectivity to existing S3 bucket and associated to RDS instance
Added `S3_INTEGRATION` RDS option to enable the feature
> Enable RDS S3 Integration

- groups/staffware-app/locals.tf
Enable ASG-level metrics for CM-1414 by defining cw_asg_level_metrics variable
> Enable ASG-level metrics

- groups/staffware-app/asg_frontend.tf
CM-1414 - add ooh actions to cloudwatch alerts for staffware
> Enable ooh actions for staffware cloudwatch

- groups/chips-rep-db/data.tf
- groups/chips-rep-db/locals.tf
Reads a list of additional cidrs for access to chips-rep DB - added for FlowMatrix application
> Add additional app cidrs access to chips-rep

- groups/staffware-db/profiles/heritage-live-eu-west-2/vars
Added Security Group pattern to permit DB access to Staffware from BIBUSOBJ
Resolves: INC0361606
> Allow BIBUSOBJ access to Staffware DB

- groups/chips-users-rest/main.tf
- groups/chips-users-rest/profiles/heritage-staging-eu-west-2/vars
- groups/chips-users-rest/variables.tf
Bumped module versions
Added vars to enable access from test subnets in Staging
Partially Resolves: INC0359993
> Allow test subnet access in Staging

- groups/oltp-logical-standby/ec2.tf
adding 256 encrypted gp3 volume to logical standby
> adding ebs vol to logical standby

- groups/oltp-logical-standby/ec2.tf
> adding ebs vol to logical standby new

- groups/staffware-rds/data.tf
- groups/staffware-rds/locals.tf
- groups/staffware-rds/main.tf
- groups/staffware-rds/outputs.tf
- groups/staffware-rds/profiles/heritage-development-eu-west-2/vars
- groups/staffware-rds/rds.tf
- groups/staffware-rds/route53.tf
- groups/staffware-rds/variables.tf
- groups/staffware-rds/vault-providers/approle
- groups/staffware-rds/vault-providers/token
- groups/staffware-rds/vault-providers/userpass
- groups/staffware-rds/vault.tf
- groups/staffware-rds/version
Added config to deploy staffware RDS instance to Heirtage Development
Updated security group config to utilise prefix lists for all rules
Resolves: CM-1520
> Deploy staffware-rds to Heritage Development

- groups/staffware-rds/profiles/heritage-development-eu-west-2/vars
Updated DB name to be `STAFFDEV` as per request
> Update DB name

- groups/chips-db-batch/profiles/heritage-live-eu-west-2/vars
- groups/chips-db-batch/profiles/heritage-staging-eu-west-2/vars
- Add changes for DPS IN and others
> CM-1492 Add changes for DPS IN and others

- groups/chips-reginit/variables.tf
> changing data volume size from 14tb to 7tb

- groups/chips-users-rest/main.tf
Resolves:
https://companieshouse.atlassian.net/browse/CM-1542
> Remove accidental change to module path

- groups/chips-db/data.tf
- groups/chips-db/ec2.tf
- groups/chips-db/profiles/heritage-staging-eu-west-2/vars
- groups/chips-db/variables.tf
- groups/chips-oem/data.tf
- groups/chips-oem/ec2.tf
- groups/chips-oem/profiles/heritage-staging-eu-west-2/vars
- groups/chips-oem/variables.tf
adding required oem ports to OLTP and clean up for the oem instance
> adding required oem ports to OLTP

- groups/oltp-logical-standby/ec2.tf
adding rport 1521 > 1522 from OEM
> adding rport 1521 > 1522 from OEM

- groups/chips-oem/data.tf
adding cidr range for dbs, this will allow the db's to talk to the oem
> adding cidr range for dbs

- groups/chips-oem/ec2.tf
- groups/chips-oem/locals.tf
adding data source for http and adding to port range. This will allow DBA to access web gui
> adding data source for http

- groups/chips-rep-db/profiles/heritage-live-eu-west-2/vars
- groups/chips-rep-db/profiles/heritage-staging-eu-west-2/vars
adding var security group for live and cleaning up var name for each instance.
> adding var security group for live

- groups/chips-db/data.tf
- groups/oltp-logical-standby/data.tf
- groups/staffware-db/data.tf
> fixing var name in data

- groups/chips-reginit/data.tf
- groups/chips-reginit/ec2.tf
- groups/chips-reginit/profiles/heritage-live-eu-west-2/vars
- groups/chips-reginit/profiles/heritage-staging-eu-west-2/vars
- groups/chips-reginit/variables.tf
adding the oem agent to the reginit build. Have added the SG to the staging vars incase its ever built there.
> adding the oem agent to the reginit build

- groups/chips-read-only/variables.tf
https://companieshouse.atlassian.net/browse/CM-1550
> Add missing ami_name var for chips-read-only group

- groups/chips-db/ec2.tf
- groups/chips-db/variables.tf
This is to support a RMAN test
> adding 2x16tb disks to oltp

- groups/chips-db/ec2.tf
- groups/chips-db/profiles/heritage-staging-eu-west-2/vars
- groups/chips-db/variables.tf
Just want the disks on one of the instances for now
> adding 2x16tb disks to oltp-01

- groups/chips-db/ec2.tf
fixing attached disk for rman2
> fixing attached disk for rman2

- groups/chips-rep-db/data.tf
- groups/chips-rep-db/locals.tf
This is for adding a new additional_internal_cidrs for ssh and application port
> adding a new data lookup with a new locals ref 

- groups/chips-ef-batch/main.tf
- groups/chips-read-only/main.tf
- groups/chips-tux-proxy/main.tf
- groups/chips-users-rest/main.tf
Update version of chips-app module version
https://companieshouse.atlassian.net/browse/DVOP-2731
> Bump version of chips-app module to 1.0.245

- groups/chips-db/data.tf
- groups/chips-db/ec2.tf
- groups/chips-db/locals.tf
Refactored security group ingress to avoid race conditions on updates with combined lists
Updated CIDR-based rules to be indexed
Replaced internal CIDRs list with prefix list-based rules
⚠️ Not to be merged until change window
> Refactor OLTP DB SG Ingress

- groups/chips-rep-db/data.tf
- groups/chips-rep-db/ec2.tf
- groups/chips-rep-db/locals.tf
Refactored security group ingress to avoid race conditions on updates with combined lists
Updated CIDR-based rules to be indexed
Replaced internal CIDRs list with prefix list-based rules
⚠️ Not to be merged until change window
> Refactor REP DB SG Ingress

- groups/chips-db-agents/data.tf
- groups/chips-db-agents/locals.tf
- groups/chips-db-agents/main.tf
- groups/chips-db-agents/profiles/heritage-live-eu-west-2/vars
- groups/chips-db-agents/profiles/heritage-staging-eu-west-2/vars
- groups/chips-db-agents/providers.tf
- groups/chips-db-agents/templates/user_data.tpl
- groups/chips-db-agents/variables.tf
- groups/chips-db-agents/version
Adds a new group chips-db-agents that provides an instance in staging & live for hosting the AppDynamics DB agents.
https://companieshouse.atlassian.net/browse/DVOP-2812
> Add chips-db-agents group

- groups/chips-db/data.tf
- groups/chips-db/ec2.tf
- groups/chips-db/profiles/heritage-staging-eu-west-2/vars
- groups/chips-db/variables.tf
- groups/chips-users-rest/data.tf
- groups/chips-users-rest/locals.tf
- groups/chips-users-rest/main.tf
Linked to SN ticket - https://companieshouse.service-now.com/now/nav/ui/classic/params/target/incident.do%3Fsys_id%3D0bb4758bc3686210d51336eb05013123%26sysparm_record_target%3Dincident%26sysparm_record_row%3D2%26sysparm_record_rows%3D5%26sysparm_record_list%3Dactive%253Dtrue%255Eassigned_to%253Djavascript%253AgetMyAssignments%2528%2529%255Estate%2521%253D6%255EORDERBYDESCsys_updated_on 
Also made some changes to line up code with what is in the console - checked with DBA Ops team and given green light to bring this back in line i.e instance type etc
> Made necessary changes to satisfy requirements of access
